-- ============================================================================
-- EDRP DEPLOYMENT — Step 2: Metadata Tables
-- ============================================================================
-- Creates all metadata tables in EDRP_METADATA schema.
-- Run as: ACCOUNTADMIN or schema owner
-- ============================================================================

USE SCHEMA DATA_REDUCTION_POC.EDRP_METADATA;

-- 1. TABLE_INVENTORY — Stores table-level metadata and reduction config
CREATE TABLE IF NOT EXISTS TABLE_INVENTORY (
    TABLE_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SOURCE_DATABASE VARCHAR(256) NOT NULL,
    SOURCE_SCHEMA VARCHAR(256) NOT NULL,
    TABLE_NAME VARCHAR(256) NOT NULL,
    TABLE_TYPE VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
    TABLE_ROLE VARCHAR(50) NOT NULL DEFAULT 'UNKNOWN',
    ROW_COUNT NUMBER(38,0),
    SIZE_BYTES NUMBER(38,0),
    PRIMARY_KEY_COLS VARCHAR(1000),
    REDUCTION_STRATEGY VARCHAR(50) DEFAULT 'SAMPLE',
    SAMPLE_PERCENT NUMBER(5,2) DEFAULT 100,
    INCLUDE_FILTER VARCHAR(4000),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    LOADED_BY VARCHAR(100) DEFAULT 'MANUAL',
    NOTES VARCHAR(4000),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    REDUCTION_ORDER NUMBER(38,0) DEFAULT 999
        COMMENT 'Graph-computed execution order (0 = process first). Set by SP_BUILD_DEPENDENCY_GRAPH.',
    SAMPLING_STRATEGY VARCHAR(30) DEFAULT 'RANDOM'
        COMMENT 'RANDOM (Bernoulli), STRATIFIED (proportional within strata), or PROPORTIONAL',
    STRATIFY_COLUMNS VARCHAR(1000)
        COMMENT 'Comma-separated column names used as stratification keys when SAMPLING_STRATEGY = STRATIFIED',
    PRIMARY KEY (TABLE_ID),
    UNIQUE (SOURCE_DATABASE, SOURCE_SCHEMA, TABLE_NAME)
);

-- 2. COLUMN_INVENTORY — Stores column-level metadata
CREATE TABLE IF NOT EXISTS COLUMN_INVENTORY (
    COLUMN_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SOURCE_DATABASE VARCHAR(256) NOT NULL,
    SOURCE_SCHEMA VARCHAR(256) NOT NULL,
    TABLE_NAME VARCHAR(256) NOT NULL,
    COLUMN_NAME VARCHAR(256) NOT NULL,
    DATA_TYPE VARCHAR(100),
    ORDINAL_POSITION NUMBER(38,0),
    IS_NULLABLE BOOLEAN DEFAULT TRUE,
    IS_PRIMARY_KEY BOOLEAN DEFAULT FALSE,
    IS_FOREIGN_KEY BOOLEAN DEFAULT FALSE,
    FK_REFERENCES VARCHAR(500),
    COLUMN_ROLE VARCHAR(50),
    SENSITIVITY_CLASS VARCHAR(50),
    DISTINCT_COUNT NUMBER(38,0),
    NULL_PERCENT NUMBER(5,2),
    LOADED_BY VARCHAR(100) DEFAULT 'MANUAL',
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (COLUMN_ID),
    UNIQUE (SOURCE_DATABASE, SOURCE_SCHEMA, TABLE_NAME, COLUMN_NAME)
);

-- 3. RELATIONSHIP_MAP — Stores table relationships (logical PK/FK mappings)
CREATE TABLE IF NOT EXISTS RELATIONSHIP_MAP (
    RELATIONSHIP_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SOURCE_DATABASE VARCHAR(256) NOT NULL,
    SOURCE_SCHEMA VARCHAR(256) NOT NULL,
    PARENT_TABLE VARCHAR(256) NOT NULL,
    PARENT_COLUMN VARCHAR(256) NOT NULL,
    CHILD_TABLE VARCHAR(256) NOT NULL,
    CHILD_COLUMN VARCHAR(256) NOT NULL,
    JOIN_TYPE VARCHAR(50) DEFAULT 'INNER',
    CARDINALITY VARCHAR(20) DEFAULT '1:N',
    IS_DECLARED_FK BOOLEAN DEFAULT FALSE,
    IS_ENFORCED BOOLEAN DEFAULT FALSE,
    CONFIDENCE VARCHAR(20) DEFAULT 'HIGH',
    RELATIONSHIP_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    DISCOVERED_BY VARCHAR(100) NOT NULL DEFAULT 'MANUAL',
    DISCOVERY_SOURCE VARCHAR(500),
    REVIEWED_BY VARCHAR(100),
    REVIEWED_AT TIMESTAMP_NTZ(9),
    NOTES VARCHAR(4000),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    IS_COMPOSITE_KEY BOOLEAN DEFAULT FALSE
        COMMENT 'TRUE if join uses multiple columns. Details in JOIN_CONDITIONS table.',
    PRIMARY KEY (RELATIONSHIP_ID),
    UNIQUE (SOURCE_DATABASE, SOURCE_SCHEMA, PARENT_TABLE, PARENT_COLUMN, CHILD_TABLE, CHILD_COLUMN)
);

-- 4. JOIN_CONDITIONS — Multi-column join support for composite keys
CREATE TABLE IF NOT EXISTS JOIN_CONDITIONS (
    CONDITION_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    RELATIONSHIP_ID NUMBER(38,0) NOT NULL COMMENT 'FK to RELATIONSHIP_MAP.RELATIONSHIP_ID',
    ORDINAL_POSITION NUMBER(38,0) NOT NULL COMMENT 'Column position within composite key (1-based)',
    PARENT_COLUMN VARCHAR(256) NOT NULL,
    CHILD_COLUMN VARCHAR(256) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    COMMENT VARCHAR(1000),
    PRIMARY KEY (CONDITION_ID)
) COMMENT = 'Stores individual column pairs for multi-column join conditions';

-- 5. REDUCTION_PROFILE — Named reduction configurations
CREATE TABLE IF NOT EXISTS REDUCTION_PROFILE (
    PROFILE_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    PROFILE_NAME VARCHAR(256) NOT NULL,
    SOURCE_DATABASE VARCHAR(256) NOT NULL,
    SOURCE_SCHEMA VARCHAR(256) NOT NULL,
    TARGET_DATABASE VARCHAR(256) NOT NULL,
    TARGET_SCHEMA VARCHAR(256) NOT NULL,
    DEFAULT_SAMPLE_PERCENT NUMBER(5,2) DEFAULT 10,
    DIMENSION_STRATEGY VARCHAR(50) DEFAULT 'FULL_COPY',
    FACT_STRATEGY VARCHAR(50) DEFAULT 'FK_CASCADE',
    PRESERVE_RARE_EVENTS BOOLEAN DEFAULT TRUE,
    RARE_EVENT_THRESHOLD NUMBER(8,6) DEFAULT 0.001,
    RANDOM_SEED NUMBER(38,0) DEFAULT 42,
    STATUS VARCHAR(20) DEFAULT 'DRAFT',
    CREATED_BY VARCHAR(100),
    APPROVED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PROFILE_ID),
    UNIQUE (PROFILE_NAME)
);

-- 6. REDUCTION_JOB_LOG — Execution audit trail
CREATE TABLE IF NOT EXISTS REDUCTION_JOB_LOG (
    JOB_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    PROFILE_ID NUMBER(38,0) NOT NULL,
    JOB_STATUS VARCHAR(20) DEFAULT 'RUNNING',
    STARTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_NTZ(9),
    TOTAL_TABLES NUMBER(38,0),
    TABLES_PROCESSED NUMBER(38,0) DEFAULT 0,
    ERROR_MESSAGE VARCHAR(4000),
    EXECUTION_LOG VARCHAR(16000000),
    TABLES_CREATED_LIST VARIANT
        COMMENT 'Array of table names successfully created in this job, used for rollback on failure',
    PRIMARY KEY (JOB_ID)
);

-- 7. REDUCTION_TABLE_LOG — Per-table execution details
CREATE TABLE IF NOT EXISTS REDUCTION_TABLE_LOG (
    LOG_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    JOB_ID NUMBER(38,0) NOT NULL,
    TABLE_NAME VARCHAR(256) NOT NULL,
    SOURCE_ROW_COUNT NUMBER(38,0),
    TARGET_ROW_COUNT NUMBER(38,0),
    REDUCTION_PERCENT NUMBER(7,4),
    STRATEGY_USED VARCHAR(50),
    EXECUTION_TIME_SEC NUMBER(10,2),
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    ERROR_MESSAGE VARCHAR(4000),
    STARTED_AT TIMESTAMP_NTZ(9),
    COMPLETED_AT TIMESTAMP_NTZ(9),
    PRIMARY KEY (LOG_ID)
);

-- 8. VALIDATION_RESULTS — FK integrity and distribution check results
CREATE TABLE IF NOT EXISTS VALIDATION_RESULTS (
    VALIDATION_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    JOB_ID NUMBER(38,0) NOT NULL,
    TABLE_NAME VARCHAR(256) NOT NULL,
    CHECK_TYPE VARCHAR(50) NOT NULL,
    CHECK_NAME VARCHAR(256) NOT NULL,
    SOURCE_VALUE VARCHAR(1000),
    TARGET_VALUE VARCHAR(1000),
    DEVIATION_PERCENT NUMBER(10,4),
    THRESHOLD_PERCENT NUMBER(10,4),
    PASS_FAIL VARCHAR(10) NOT NULL,
    DETAILS VARCHAR(4000),
    CHECKED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (VALIDATION_ID)
);
