-- ============================================================================
-- EDRP DEPLOYMENT — Step 4: Views
-- ============================================================================
-- Creates reporting views on metadata tables.
-- Run as: ACCOUNTADMIN or EDRP_ADMIN
-- ============================================================================

USE SCHEMA DATA_REDUCTION_POC.EDRP_METADATA;

-- 4.1 V_RELATIONSHIP_LINEAGE — Recursive dependency tree
CREATE OR REPLACE VIEW V_RELATIONSHIP_LINEAGE AS
WITH RECURSIVE lineage AS (
    SELECT
        r.PARENT_TABLE AS TABLE_NAME,
        CAST(NULL AS VARCHAR) AS PARENT_TABLE,
        CAST(NULL AS VARCHAR) AS PARENT_COLUMN,
        CAST(NULL AS VARCHAR) AS CHILD_COLUMN,
        0 AS DEPTH,
        r.PARENT_TABLE AS ROOT_TABLE,
        r.SOURCE_DATABASE,
        r.SOURCE_SCHEMA
    FROM RELATIONSHIP_MAP r
    WHERE r.RELATIONSHIP_STATUS = 'ACTIVE'
      AND r.PARENT_TABLE NOT IN (
          SELECT CHILD_TABLE FROM RELATIONSHIP_MAP
          WHERE RELATIONSHIP_STATUS = 'ACTIVE'
            AND SOURCE_DATABASE = r.SOURCE_DATABASE
            AND SOURCE_SCHEMA = r.SOURCE_SCHEMA
      )
    GROUP BY r.PARENT_TABLE, r.SOURCE_DATABASE, r.SOURCE_SCHEMA
    
    UNION ALL
    
    SELECT
        r.CHILD_TABLE AS TABLE_NAME, r.PARENT_TABLE, r.PARENT_COLUMN, r.CHILD_COLUMN,
        l.DEPTH + 1 AS DEPTH, l.ROOT_TABLE, r.SOURCE_DATABASE, r.SOURCE_SCHEMA
    FROM RELATIONSHIP_MAP r
    JOIN lineage l ON r.PARENT_TABLE = l.TABLE_NAME
        AND r.SOURCE_DATABASE = l.SOURCE_DATABASE AND r.SOURCE_SCHEMA = l.SOURCE_SCHEMA
    WHERE r.RELATIONSHIP_STATUS = 'ACTIVE' AND l.DEPTH < 10
)
SELECT
    l.SOURCE_DATABASE, l.SOURCE_SCHEMA, l.ROOT_TABLE, l.DEPTH,
    REPEAT('  ', l.DEPTH) || l.TABLE_NAME AS HIERARCHY_DISPLAY,
    l.TABLE_NAME, l.PARENT_TABLE,
    COALESCE(l.PARENT_COLUMN || ' -> ' || l.CHILD_COLUMN, '(root)') AS JOIN_PATH,
    COALESCE(r.IS_COMPOSITE_KEY, FALSE) AS IS_COMPOSITE_KEY,
    COALESCE(r.CARDINALITY, '-') AS CARDINALITY,
    t.REDUCTION_STRATEGY, t.SAMPLE_PERCENT, t.SAMPLING_STRATEGY
FROM lineage l
LEFT JOIN RELATIONSHIP_MAP r
    ON r.PARENT_TABLE = l.PARENT_TABLE AND r.CHILD_TABLE = l.TABLE_NAME
    AND r.SOURCE_DATABASE = l.SOURCE_DATABASE AND r.SOURCE_SCHEMA = l.SOURCE_SCHEMA
    AND r.RELATIONSHIP_STATUS = 'ACTIVE'
LEFT JOIN TABLE_INVENTORY t
    ON t.TABLE_NAME = l.TABLE_NAME AND t.SOURCE_DATABASE = l.SOURCE_DATABASE
    AND t.SOURCE_SCHEMA = l.SOURCE_SCHEMA
ORDER BY l.SOURCE_DATABASE, l.SOURCE_SCHEMA, l.ROOT_TABLE, l.DEPTH, l.TABLE_NAME;


-- 4.2 V_CATEGORICAL_COVERAGE — Distribution deviation report per job
CREATE OR REPLACE VIEW V_CATEGORICAL_COVERAGE AS
SELECT
    v.JOB_ID, v.TABLE_NAME,
    v.CHECK_NAME AS COLUMN_CHECK,
    v.DEVIATION_PERCENT, v.THRESHOLD_PERCENT,
    v.PASS_FAIL, v.DETAILS, v.CHECKED_AT
FROM VALIDATION_RESULTS v
WHERE v.CHECK_TYPE = 'DISTRIBUTION'
ORDER BY v.JOB_ID DESC, v.PASS_FAIL, v.TABLE_NAME;
