-- ============================================================================
-- EDRP DEPLOYMENT — Step 5: RBAC Setup
-- ============================================================================
-- Creates EDRP roles and grants. Adjust database name if deploying elsewhere.
-- Run as: ACCOUNTADMIN or SECURITYADMIN
-- ============================================================================

-- 1. Create Roles
CREATE ROLE IF NOT EXISTS EDRP_ADMIN;
CREATE ROLE IF NOT EXISTS EDRP_OPERATOR;
CREATE ROLE IF NOT EXISTS EDRP_VIEWER;

-- 2. Role Hierarchy
GRANT ROLE EDRP_VIEWER TO ROLE EDRP_OPERATOR;
GRANT ROLE EDRP_OPERATOR TO ROLE EDRP_ADMIN;
GRANT ROLE EDRP_ADMIN TO ROLE SYSADMIN;

-- 3. Database & Schema Usage (Viewer)
GRANT USAGE ON DATABASE DATA_REDUCTION_POC TO ROLE EDRP_VIEWER;
GRANT USAGE ON SCHEMA DATA_REDUCTION_POC.EDRP_METADATA TO ROLE EDRP_VIEWER;
GRANT USAGE ON SCHEMA DATA_REDUCTION_POC.EDRP_APP TO ROLE EDRP_VIEWER;
GRANT USAGE ON SCHEMA DATA_REDUCTION_POC.STAGE_DATA_REDUCED TO ROLE EDRP_VIEWER;

-- 4. Viewer: read metadata and reduced data
GRANT SELECT ON ALL TABLES IN SCHEMA DATA_REDUCTION_POC.EDRP_METADATA TO ROLE EDRP_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA DATA_REDUCTION_POC.EDRP_METADATA TO ROLE EDRP_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA DATA_REDUCTION_POC.STAGE_DATA_REDUCED TO ROLE EDRP_VIEWER;

-- 5. Operator: execute procedures + warehouse
GRANT USAGE ON WAREHOUSE EDRP_WH TO ROLE EDRP_OPERATOR;
GRANT USAGE ON PROCEDURE DATA_REDUCTION_POC.EDRP_APP.SP_EXECUTE_REDUCTION(VARCHAR) TO ROLE EDRP_OPERATOR;
GRANT USAGE ON PROCEDURE DATA_REDUCTION_POC.EDRP_APP.SP_VALIDATE_REDUCTION(NUMBER) TO ROLE EDRP_OPERATOR;
GRANT USAGE ON PROCEDURE DATA_REDUCTION_POC.EDRP_APP.SP_ROLLBACK_REDUCTION(NUMBER) TO ROLE EDRP_OPERATOR;

-- 6. Admin: full control
GRANT ALL ON SCHEMA DATA_REDUCTION_POC.EDRP_METADATA TO ROLE EDRP_ADMIN;
GRANT ALL ON SCHEMA DATA_REDUCTION_POC.EDRP_APP TO ROLE EDRP_ADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA DATA_REDUCTION_POC.EDRP_METADATA TO ROLE EDRP_ADMIN;

-- 7. Future grants (so new objects inherit permissions)
GRANT SELECT ON FUTURE TABLES IN SCHEMA DATA_REDUCTION_POC.EDRP_METADATA TO ROLE EDRP_VIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DATA_REDUCTION_POC.EDRP_METADATA TO ROLE EDRP_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DATA_REDUCTION_POC.STAGE_DATA_REDUCED TO ROLE EDRP_VIEWER;
