-- ============================================================================
-- EDRP VALIDATION QUERIES
-- Enterprise Data Reduction Platform — Comprehensive Validation Suite
-- ============================================================================
-- Usage: Run these queries after SP_EXECUTE_REDUCTION completes.
--        Replace JOB_ID value (101) with your actual job ID.
-- ============================================================================

USE DATABASE DATA_REDUCTION_POC;
USE WAREHOUSE COMPUTE_WH;

-- ============================================================================
-- 1. JOB EXECUTION SUMMARY
-- ============================================================================

-- 1a. Job status and timing
SELECT
    j.JOB_ID,
    p.PROFILE_NAME,
    p.SOURCE_DATABASE || '.' || p.SOURCE_SCHEMA AS SOURCE,
    p.TARGET_DATABASE || '.' || p.TARGET_SCHEMA AS TARGET,
    j.JOB_STATUS,
    j.TOTAL_TABLES,
    j.TABLES_PROCESSED,
    j.STARTED_AT,
    j.COMPLETED_AT,
    DATEDIFF('second', j.STARTED_AT, j.COMPLETED_AT) AS DURATION_SEC
FROM EDRP_METADATA.REDUCTION_JOB_LOG j
JOIN EDRP_METADATA.REDUCTION_PROFILE p ON j.PROFILE_ID = p.PROFILE_ID
ORDER BY j.JOB_ID DESC
LIMIT 5;

-- 1b. Per-table execution details for most recent job
SELECT
    TABLE_NAME,
    STRATEGY_USED,
    SOURCE_ROW_COUNT,
    TARGET_ROW_COUNT,
    REDUCTION_PERCENT || '%' AS REDUCTION_PCT,
    ROUND(EXECUTION_TIME_SEC, 1) AS TIME_SEC,
    STATUS
FROM EDRP_METADATA.REDUCTION_TABLE_LOG
WHERE JOB_ID = (SELECT MAX(JOB_ID) FROM EDRP_METADATA.REDUCTION_JOB_LOG)
ORDER BY
    CASE STATUS WHEN 'FAILED' THEN 0 WHEN 'COMPLETED' THEN 1 ELSE 2 END,
    SOURCE_ROW_COUNT DESC;

-- 1c. Aggregate reduction stats
SELECT
    COUNT(*) AS TOTAL_TABLES,
    SUM(CASE WHEN STATUS = 'COMPLETED' THEN 1 ELSE 0 END) AS COMPLETED,
    SUM(CASE WHEN STATUS = 'FAILED' THEN 1 ELSE 0 END) AS FAILED,
    SUM(SOURCE_ROW_COUNT) AS TOTAL_SOURCE_ROWS,
    SUM(TARGET_ROW_COUNT) AS TOTAL_TARGET_ROWS,
    ROUND(100 - (SUM(TARGET_ROW_COUNT) * 100.0 / NULLIF(SUM(SOURCE_ROW_COUNT), 0)), 2) AS OVERALL_REDUCTION_PCT,
    ROUND(SUM(EXECUTION_TIME_SEC), 1) AS TOTAL_TIME_SEC
FROM EDRP_METADATA.REDUCTION_TABLE_LOG
WHERE JOB_ID = (SELECT MAX(JOB_ID) FROM EDRP_METADATA.REDUCTION_JOB_LOG);


-- ============================================================================
-- 2. FK INTEGRITY CHECKS — Zero Orphaned Records
-- ============================================================================

-- 2a. Summary of FK validation results
SELECT
    PASS_FAIL,
    COUNT(*) AS CHECK_COUNT
FROM EDRP_METADATA.VALIDATION_RESULTS
WHERE JOB_ID = (SELECT MAX(JOB_ID) FROM EDRP_METADATA.REDUCTION_JOB_LOG)
  AND CHECK_TYPE = 'FK_INTEGRITY'
GROUP BY PASS_FAIL
ORDER BY PASS_FAIL;

-- 2b. Failed FK checks (orphaned records)
SELECT
    TABLE_NAME,
    CHECK_NAME,
    TARGET_VALUE AS ORPHAN_DETAIL,
    DETAILS
FROM EDRP_METADATA.VALIDATION_RESULTS
WHERE JOB_ID = (SELECT MAX(JOB_ID) FROM EDRP_METADATA.REDUCTION_JOB_LOG)
  AND CHECK_TYPE = 'FK_INTEGRITY'
  AND PASS_FAIL = 'FAIL'
ORDER BY TABLE_NAME;

-- 2c. All FK checks — full detail
SELECT
    TABLE_NAME,
    CHECK_NAME,
    PASS_FAIL,
    TARGET_VALUE AS ORPHAN_COUNT,
    DETAILS
FROM EDRP_METADATA.VALIDATION_RESULTS
WHERE JOB_ID = (SELECT MAX(JOB_ID) FROM EDRP_METADATA.REDUCTION_JOB_LOG)
  AND CHECK_TYPE = 'FK_INTEGRITY'
ORDER BY PASS_FAIL DESC, TABLE_NAME;





-- ============================================================================
-- 3. MANUAL FK SPOT CHECKS — Run Against Reduced Data Directly
-- ============================================================================
-- These queries verify referential integrity by counting orphaned foreign keys
-- in the reduced target schema. Every count should be 0.

-- 3a. STORE_RETURNS → CUSTOMER (SR_CUSTOMER_SK)
SELECT 'STORE_RETURNS.SR_CUSTOMER_SK' AS FK_CHECK,
       COUNT(*) AS ORPHAN_COUNT
FROM STAGE_DATA_REDUCED.STORE_RETURNS sr
WHERE sr.SR_CUSTOMER_SK IS NOT NULL
  AND sr.SR_CUSTOMER_SK NOT IN (
      SELECT C_CUSTOMER_SK FROM STAGE_DATA_REDUCED.CUSTOMER
  );

-- 3b. CATALOG_RETURNS → CUSTOMER (CR_REFUNDED_CUSTOMER_SK)
SELECT 'CATALOG_RETURNS.CR_REFUNDED_CUSTOMER_SK' AS FK_CHECK,
       COUNT(*) AS ORPHAN_COUNT
FROM STAGE_DATA_REDUCED.CATALOG_RETURNS cr
WHERE cr.CR_REFUNDED_CUSTOMER_SK IS NOT NULL
  AND cr.CR_REFUNDED_CUSTOMER_SK NOT IN (
      SELECT C_CUSTOMER_SK FROM STAGE_DATA_REDUCED.CUSTOMER
  );

-- 3c. WEB_RETURNS → CUSTOMER (WR_RETURNING_CUSTOMER_SK)
SELECT 'WEB_RETURNS.WR_RETURNING_CUSTOMER_SK' AS FK_CHECK,
       COUNT(*) AS ORPHAN_COUNT
FROM STAGE_DATA_REDUCED.WEB_RETURNS wr
WHERE wr.WR_RETURNING_CUSTOMER_SK IS NOT NULL
  AND wr.WR_RETURNING_CUSTOMER_SK NOT IN (
      SELECT C_CUSTOMER_SK FROM STAGE_DATA_REDUCED.CUSTOMER
  );

-- 3d. STORE_RETURNS → ITEM (SR_ITEM_SK)
SELECT 'STORE_RETURNS.SR_ITEM_SK' AS FK_CHECK,
       COUNT(*) AS ORPHAN_COUNT
FROM STAGE_DATA_REDUCED.STORE_RETURNS sr
WHERE sr.SR_ITEM_SK IS NOT NULL
  AND sr.SR_ITEM_SK NOT IN (
      SELECT I_ITEM_SK FROM STAGE_DATA_REDUCED.ITEM
  );

-- 3e. INVENTORY → DATE_DIM (INV_DATE_SK)
SELECT 'INVENTORY.INV_DATE_SK' AS FK_CHECK,
       COUNT(*) AS ORPHAN_COUNT
FROM STAGE_DATA_REDUCED.INVENTORY inv
WHERE inv.INV_DATE_SK IS NOT NULL
  AND inv.INV_DATE_SK NOT IN (
      SELECT D_DATE_SK FROM STAGE_DATA_REDUCED.DATE_DIM
  );

-- 3f. CATALOG_RETURNS → CALL_CENTER (CR_CALL_CENTER_SK)
SELECT 'CATALOG_RETURNS.CR_CALL_CENTER_SK' AS FK_CHECK,
       COUNT(*) AS ORPHAN_COUNT
FROM STAGE_DATA_REDUCED.CATALOG_RETURNS cr
WHERE cr.CR_CALL_CENTER_SK IS NOT NULL
  AND cr.CR_CALL_CENTER_SK NOT IN (
      SELECT CC_CALL_CENTER_SK FROM STAGE_DATA_REDUCED.CALL_CENTER
  );


-- ============================================================================
-- 4. ROW COUNT COMPARISON — Source vs. Reduced
-- ============================================================================

-- 4a. Side-by-side row counts with reduction percentage
SELECT
    t.TABLE_NAME,
    t.REDUCTION_STRATEGY,
    t.SAMPLING_STRATEGY,
    s.ROW_COUNT AS SOURCE_ROWS,
    r.ROW_COUNT AS REDUCED_ROWS,
    ROUND(100 - (r.ROW_COUNT * 100.0 / NULLIF(s.ROW_COUNT, 0)), 2) AS REDUCTION_PCT
FROM EDRP_METADATA.TABLE_INVENTORY t
LEFT JOIN INFORMATION_SCHEMA.TABLES s
    ON s.TABLE_SCHEMA = 'STAGE_DATA' AND s.TABLE_NAME = t.TABLE_NAME
LEFT JOIN INFORMATION_SCHEMA.TABLES r
    ON r.TABLE_SCHEMA = 'STAGE_DATA_REDUCED' AND r.TABLE_NAME = t.TABLE_NAME
WHERE t.SOURCE_DATABASE = 'DATA_REDUCTION_POC'
  AND t.SOURCE_SCHEMA = 'STAGE_DATA'
ORDER BY s.ROW_COUNT DESC;


-- ============================================================================
-- 5. DISTRIBUTION CHECKS — Categorical Value Preservation
-- ============================================================================

-- 5a. Distribution validation results from automated checks
SELECT * FROM EDRP_METADATA.V_CATEGORICAL_COVERAGE
WHERE JOB_ID = (SELECT MAX(JOB_ID) FROM EDRP_METADATA.REDUCTION_JOB_LOG);

-- 5b. Manual: CUSTOMER_DEMOGRAPHICS distribution (CD_GENDER)
SELECT
    'SOURCE' AS DATASET, CD_GENDER,
    COUNT(*) AS CNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PCT
FROM STAGE_DATA.CUSTOMER_DEMOGRAPHICS GROUP BY CD_GENDER
UNION ALL
SELECT
    'REDUCED', CD_GENDER,
    COUNT(*),
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2)
FROM STAGE_DATA_REDUCED.CUSTOMER_DEMOGRAPHICS GROUP BY CD_GENDER
ORDER BY CD_GENDER, DATASET;

-- 5c. Manual: STORE distribution (S_STATE)
SELECT
    'SOURCE' AS DATASET, S_STATE,
    COUNT(*) AS CNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PCT
FROM STAGE_DATA.STORE GROUP BY S_STATE
UNION ALL
SELECT
    'REDUCED', S_STATE,
    COUNT(*),
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2)
FROM STAGE_DATA_REDUCED.STORE GROUP BY S_STATE
ORDER BY S_STATE, DATASET;

-- 5d. Manual: REASON distribution (R_REASON_DESC)
SELECT
    'SOURCE' AS DATASET, R_REASON_DESC,
    COUNT(*) AS CNT
FROM STAGE_DATA.REASON GROUP BY R_REASON_DESC
UNION ALL
SELECT
    'REDUCED', R_REASON_DESC,
    COUNT(*)
FROM STAGE_DATA_REDUCED.REASON GROUP BY R_REASON_DESC
ORDER BY R_REASON_DESC, DATASET;

-- 5e. Distinct value counts — source vs reduced (no values lost?)
SELECT
    'CUSTOMER_DEMOGRAPHICS.CD_GENDER' AS COLUMN_CHECK,
    (SELECT COUNT(DISTINCT CD_GENDER) FROM STAGE_DATA.CUSTOMER_DEMOGRAPHICS) AS SOURCE_DISTINCT,
    (SELECT COUNT(DISTINCT CD_GENDER) FROM STAGE_DATA_REDUCED.CUSTOMER_DEMOGRAPHICS) AS REDUCED_DISTINCT
UNION ALL
SELECT
    'CUSTOMER_DEMOGRAPHICS.CD_MARITAL_STATUS',
    (SELECT COUNT(DISTINCT CD_MARITAL_STATUS) FROM STAGE_DATA.CUSTOMER_DEMOGRAPHICS),
    (SELECT COUNT(DISTINCT CD_MARITAL_STATUS) FROM STAGE_DATA_REDUCED.CUSTOMER_DEMOGRAPHICS)
UNION ALL
SELECT
    'CUSTOMER_DEMOGRAPHICS.CD_EDUCATION_STATUS',
    (SELECT COUNT(DISTINCT CD_EDUCATION_STATUS) FROM STAGE_DATA.CUSTOMER_DEMOGRAPHICS),
    (SELECT COUNT(DISTINCT CD_EDUCATION_STATUS) FROM STAGE_DATA_REDUCED.CUSTOMER_DEMOGRAPHICS)
UNION ALL
SELECT
    'INCOME_BAND.IB_LOWER_BOUND',
    (SELECT COUNT(DISTINCT IB_LOWER_BOUND) FROM STAGE_DATA.INCOME_BAND),
    (SELECT COUNT(DISTINCT IB_LOWER_BOUND) FROM STAGE_DATA_REDUCED.INCOME_BAND)
UNION ALL
SELECT
    'SHIP_MODE.SM_TYPE',
    (SELECT COUNT(DISTINCT SM_TYPE) FROM STAGE_DATA.SHIP_MODE),
    (SELECT COUNT(DISTINCT SM_TYPE) FROM STAGE_DATA_REDUCED.SHIP_MODE)
UNION ALL
SELECT
    'REASON.R_REASON_DESC',
    (SELECT COUNT(DISTINCT R_REASON_DESC) FROM STAGE_DATA.REASON),
    (SELECT COUNT(DISTINCT R_REASON_DESC) FROM STAGE_DATA_REDUCED.REASON);


-- ============================================================================
-- 6. RELATIONSHIP LINEAGE — Dependency Tree
-- ============================================================================

-- 6a. Full hierarchy view
SELECT DISTINCT
    ROOT_TABLE,
    DEPTH,
    HIERARCHY_DISPLAY,
    JOIN_PATH,
    CARDINALITY,
    REDUCTION_STRATEGY,
    SAMPLING_STRATEGY
FROM EDRP_METADATA.V_RELATIONSHIP_LINEAGE
WHERE SOURCE_DATABASE = 'DATA_REDUCTION_POC'
  AND SOURCE_SCHEMA = 'STAGE_DATA'
ORDER BY ROOT_TABLE, DEPTH, HIERARCHY_DISPLAY;

-- 6b. Tables by dependency depth (how deep is the chain?)
SELECT
    DEPTH,
    COUNT(DISTINCT TABLE_NAME) AS TABLE_COUNT,
    LISTAGG(DISTINCT TABLE_NAME, ', ') WITHIN GROUP (ORDER BY TABLE_NAME) AS TABLES
FROM EDRP_METADATA.V_RELATIONSHIP_LINEAGE
WHERE SOURCE_DATABASE = 'DATA_REDUCTION_POC'
  AND SOURCE_SCHEMA = 'STAGE_DATA'
GROUP BY DEPTH
ORDER BY DEPTH;


-- ============================================================================
-- 7. METADATA HEALTH CHECKS
-- ============================================================================

-- 7a. Tables with no relationships defined
SELECT t.TABLE_NAME, t.TABLE_TYPE, t.TABLE_ROLE, t.REDUCTION_STRATEGY
FROM EDRP_METADATA.TABLE_INVENTORY t
LEFT JOIN EDRP_METADATA.RELATIONSHIP_MAP r
    ON (r.PARENT_TABLE = t.TABLE_NAME OR r.CHILD_TABLE = t.TABLE_NAME)
    AND r.SOURCE_DATABASE = t.SOURCE_DATABASE
    AND r.SOURCE_SCHEMA = t.SOURCE_SCHEMA
    AND r.RELATIONSHIP_STATUS = 'ACTIVE'
WHERE t.SOURCE_DATABASE = 'DATA_REDUCTION_POC'
  AND t.SOURCE_SCHEMA = 'STAGE_DATA'
  AND r.RELATIONSHIP_ID IS NULL;

-- 7b. Relationship map summary
SELECT
    RELATIONSHIP_STATUS,
    DISCOVERED_BY,
    COUNT(*) AS REL_COUNT
FROM EDRP_METADATA.RELATIONSHIP_MAP
WHERE SOURCE_DATABASE = 'DATA_REDUCTION_POC'
  AND SOURCE_SCHEMA = 'STAGE_DATA'
GROUP BY RELATIONSHIP_STATUS, DISCOVERED_BY
ORDER BY RELATIONSHIP_STATUS, DISCOVERED_BY;

-- 7c. Reduction strategy distribution
SELECT
    REDUCTION_STRATEGY,
    COUNT(*) AS TABLE_COUNT,
    LISTAGG(TABLE_NAME, ', ') WITHIN GROUP (ORDER BY TABLE_NAME) AS TABLES
FROM EDRP_METADATA.TABLE_INVENTORY
WHERE SOURCE_DATABASE = 'DATA_REDUCTION_POC'
  AND SOURCE_SCHEMA = 'STAGE_DATA'
GROUP BY REDUCTION_STRATEGY
ORDER BY TABLE_COUNT DESC;

-- 7d. Graph execution order
SELECT
    REDUCTION_ORDER,
    TABLE_NAME,
    TABLE_ROLE,
    REDUCTION_STRATEGY,
    SAMPLE_PERCENT
FROM EDRP_METADATA.TABLE_INVENTORY
WHERE SOURCE_DATABASE = 'DATA_REDUCTION_POC'
  AND SOURCE_SCHEMA = 'STAGE_DATA'
ORDER BY REDUCTION_ORDER;


-- ============================================================================
-- 8. ROLLBACK SUPPORT — Tables Created Per Job
-- ============================================================================

SELECT
    JOB_ID,
    JOB_STATUS,
    ARRAY_SIZE(COALESCE(TABLES_CREATED_LIST, PARSE_JSON('[]'))) AS TABLES_CREATED,
    TABLES_CREATED_LIST
FROM EDRP_METADATA.REDUCTION_JOB_LOG
ORDER BY JOB_ID DESC
LIMIT 5;


-- ============================================================================
-- 9. ALL VALIDATION RESULTS — Full Audit Log
-- ============================================================================

SELECT
    JOB_ID,
    TABLE_NAME,
    CHECK_TYPE,
    CHECK_NAME,
    PASS_FAIL,
    COALESCE(DEVIATION_PERCENT::VARCHAR, TARGET_VALUE) AS RESULT_DETAIL,
    DETAILS,
    CHECKED_AT
FROM EDRP_METADATA.VALIDATION_RESULTS
WHERE JOB_ID = (SELECT MAX(JOB_ID) FROM EDRP_METADATA.REDUCTION_JOB_LOG)
ORDER BY
    CASE PASS_FAIL WHEN 'FAIL' THEN 0 WHEN 'WARN' THEN 1 ELSE 2 END,
    CHECK_TYPE,
    TABLE_NAME;


-- ============================================================================
-- 10. CATEGORICAL COVERAGE VALIDATION — Stratified Sampling Proof
-- ============================================================================
-- These queries prove that all distinct categorical values survive reduction.
-- Run after configuring STRATIFY_COLUMNS in TABLE_INVENTORY.

-- 10a. CUSTOMER.C_BIRTH_COUNTRY — Distinct value count comparison
SELECT
    'SOURCE' AS DATASET,
    COUNT(DISTINCT C_BIRTH_COUNTRY) AS DISTINCT_COUNTRIES,
    COUNT(*) AS TOTAL_ROWS
FROM DATA_REDUCTION_POC.STAGE_DATA.CUSTOMER
UNION ALL
SELECT
    'REDUCED',
    COUNT(DISTINCT C_BIRTH_COUNTRY),
    COUNT(*)
FROM DATA_REDUCTION_POC.STAGE_DATA_REDUCED.CUSTOMER
ORDER BY DATASET DESC;

-- 10b. Per-country row counts — verify proportional representation
WITH src AS (
    SELECT C_BIRTH_COUNTRY, COUNT(*) AS SRC_CNT
    FROM DATA_REDUCTION_POC.STAGE_DATA.CUSTOMER
    GROUP BY C_BIRTH_COUNTRY
),
tgt AS (
    SELECT C_BIRTH_COUNTRY, COUNT(*) AS TGT_CNT
    FROM DATA_REDUCTION_POC.STAGE_DATA_REDUCED.CUSTOMER
    GROUP BY C_BIRTH_COUNTRY
)
SELECT
    s.C_BIRTH_COUNTRY,
    s.SRC_CNT AS SOURCE_ROWS,
    t.TGT_CNT AS REDUCED_ROWS,
    ROUND(t.TGT_CNT * 100.0 / s.SRC_CNT, 2) AS SAMPLE_PCT,
    CASE WHEN t.TGT_CNT IS NULL THEN 'MISSING' ELSE 'OK' END AS STATUS
FROM src s
LEFT JOIN tgt t ON s.C_BIRTH_COUNTRY = t.C_BIRTH_COUNTRY
ORDER BY s.SRC_CNT ASC;

-- 10c. Missing countries check — should return 0 rows
SELECT s.C_BIRTH_COUNTRY AS MISSING_COUNTRY, s.CNT AS SOURCE_ROWS
FROM (
    SELECT C_BIRTH_COUNTRY, COUNT(*) AS CNT
    FROM DATA_REDUCTION_POC.STAGE_DATA.CUSTOMER
    GROUP BY C_BIRTH_COUNTRY
) s
LEFT JOIN (
    SELECT DISTINCT C_BIRTH_COUNTRY
    FROM DATA_REDUCTION_POC.STAGE_DATA_REDUCED.CUSTOMER
) t ON s.C_BIRTH_COUNTRY = t.C_BIRTH_COUNTRY
WHERE t.C_BIRTH_COUNTRY IS NULL;

-- 10d. Generic template — validate any categorical column
-- Replace <SCHEMA>, <TABLE>, <COLUMN> with your values
/*
SELECT
    'SOURCE' AS DATASET,
    COUNT(DISTINCT <COLUMN>) AS DISTINCT_VALUES,
    COUNT(*) AS TOTAL_ROWS
FROM DATA_REDUCTION_POC.<SOURCE_SCHEMA>.<TABLE>
UNION ALL
SELECT
    'REDUCED',
    COUNT(DISTINCT <COLUMN>),
    COUNT(*)
FROM DATA_REDUCTION_POC.<TARGET_SCHEMA>.<TABLE>
ORDER BY DATASET DESC;
*/

-- 10e. Stratified sampling config — what's currently configured?
SELECT
    TABLE_NAME,
    REDUCTION_STRATEGY,
    SAMPLING_STRATEGY,
    STRATIFY_COLUMNS,
    SAMPLE_PERCENT
FROM DATA_REDUCTION_POC.EDRP_METADATA.TABLE_INVENTORY
WHERE SOURCE_DATABASE = 'DATA_REDUCTION_POC'
  AND SOURCE_SCHEMA = 'STAGE_DATA'
  AND SAMPLING_STRATEGY = 'STRATIFIED';
